// Generated by CoffeeScript 1.7.1
(function() {
  var Action, DataMaperAction, objval,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Action = require('../action');

  objval = require('../../util/objval');

  DataMaperAction = (function(_super) {
    var mapData;

    __extends(DataMaperAction, _super);

    function DataMaperAction(map) {
      this.map = map;
    }

    DataMaperAction.prototype.onExec = function(data, callback) {
      return callback('success', mapData(data, this.map));
    };

    mapData = function(data, map) {
      var key, retval, srcKey;
      retval = {};
      for (key in map) {
        srcKey = map[key];
        if (typeof srcKey === 'object') {
          retval[key] = mapData(data, srcKey);
        }
        if (typeof srcKey === 'string') {
          retval[key] = objval(data, srcKey);
        }
      }
      return retval;
    };

    return DataMaperAction;

  })(Action);

  module.exports = DataMaperAction;

}).call(this);
