// Generated by CoffeeScript 1.7.1
(function() {
  var Action, ValidateAction, ValidationManager, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Action = require('../action');

  _ = require('underscore');

  ValidationManager = require('../../validation');

  ValidateAction = (function(_super) {
    __extends(ValidateAction, _super);

    function ValidateAction() {
      this.validationManger = new ValidationManager;
    }

    ValidateAction.prototype.add = function(field, validator) {
      return this.validationManger.addValidator(field, validator);
    };

    ValidateAction.prototype.onExec = function(data, callback) {
      var err, res, _i, _len, _ref;
      res = this.validationManger.validate(data);
      if (!((data.errors != null) && data.errors instanceof Array)) {
        data.errors = [];
      }
      _ref = this.validationManger.getErrors();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        err = _ref[_i];
        data.errors.push(err);
      }
      return callback((res ? "success" : "failed"), data);
    };

    return ValidateAction;

  })(Action);

  module.exports = ValidateAction;

}).call(this);
