// Generated by CoffeeScript 1.7.1
(function() {
  var APIBackend, restify;

  restify = require('restify');

  APIBackend = (function() {
    function APIBackend(baseURI) {
      this.client = restify.createJSONClient({
        url: baseURI
      });
    }

    APIBackend.prototype.get = function(path, callback) {
      return this.client.get(path, function(e, req, res, obj) {
        return callback(e, obj);
      });
    };

    APIBackend.prototype.post = function(path, params, callback) {
      return this.client.post(path, params, function(e, req, res, obj) {
        return callback(e, obj);
      });
    };

    APIBackend.prototype.put = function(path, params, callback) {
      return this.client.put(path, params, function(e, req, res, obj) {
        return callback(e, obj);
      });
    };

    APIBackend.prototype["delete"] = function(path, callback) {
      return this.client["delete"](path, function(e, req, res, obj) {
        return callback(e, obj);
      });
    };

    APIBackend.prototype.head = function(path, callback) {
      return this.client.head(path, function(e, req, res, obj) {
        return callback(e, obj);
      });
    };

    return APIBackend;

  })();

  module.exports = APIBackend;

}).call(this);
