// Generated by CoffeeScript 1.7.1
(function() {
  var APICall, ManagedAPICall,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  APICall = require('./call');

  ManagedAPICall = (function(_super) {
    __extends(ManagedAPICall, _super);

    function ManagedAPICall() {
      return ManagedAPICall.__super__.constructor.apply(this, arguments);
    }

    ManagedAPICall.prototype.exec = function(data, callback) {
      this.status = {
        start: new Date
      };
      ManagedAPICall.__super__.exec.call(this, data, (function(_this) {
        return function(e, resp) {
          _this.status.end = new Date;
          if (e != null) {
            _this.status.error = e.code;
          }
          return _this.onComplete(e, resp);
        };
      })(this));
      return callback(null, {
        status: 'initialized'
      });
    };

    ManagedAPICall.prototype.onComplete = function(e, response) {
      return console.log("Nothing to do on complete");
    };

    return ManagedAPICall;

  })(APICall);

  module.exports = ManagedAPICall;

}).call(this);
