// Generated by CoffeeScript 1.7.1
var Memcache, Memcached,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Memcached = require('memcached');

Memcache = (function() {
  function Memcache(memcacheServerUrl, options) {
    this.set = __bind(this.set, this);
    this.memcached = new Memcached(memcacheServerUrl, options);
  }

  Memcache.prototype.get = function(key, callback) {
    return this.memcached.get(key, callback);
  };

  Memcache.prototype.set = function(key, callback) {
    var cb;
    cb = (function(_this) {
      return function(val, ttl, innerCallback) {
        return _this.memcached.set(key, val, ttl, innerCallback);
      };
    })(this);
    return callback(cb);
  };

  return Memcache;

})();

module.exports = Memcache;
