// Generated by CoffeeScript 1.7.1
(function() {
  var State;

  State = (function() {
    function State(name) {
      this.name = name;
    }

    State.prototype.getName = function() {
      return this.name;
    };

    State.prototype.setLogger = function(logger) {};

    State.prototype.setAction = function(action) {
      return this.action = action;
    };

    State.prototype.enter = function(data, callback) {
      if (this.action == null) {
        callback('undefined_action', data);
      }
      return this.action.exec(data, callback);
    };

    return State;

  })();

  module.exports = State;

}).call(this);
