// Generated by CoffeeScript 1.7.1
var Database;

Database = (function() {
  function Database() {
    throw Error("Implementations shoud have the contructor set up the Database");
  }

  Database.prototype.registerSchema = function() {
    throw Error("Implementations shoud have the registerSchema");
  };

  return Database;

})();

module.exports = Database;
