// Generated by CoffeeScript 1.7.1
var DBInterface;

DBInterface = (function() {
  function DBInterface(schema) {
    throw Error("Implementations shoud have the contructor to set up the DBInterface");
  }

  DBInterface.prototype.create = function(data, cb) {
    throw Error("Implementations shoud have create to set up the DBInterface");
  };

  DBInterface.prototype.read = function(criteria, cb) {
    throw Error("Implementations shoud have read to set up the DBInterface");
  };

  DBInterface.prototype.readAll = function(criteria, cb) {
    throw Error("Implementations shoud have readAll to set up the DBInterface");
  };

  DBInterface.prototype.update = function(criteria, data, options, cb) {
    throw Error("Implementations shoud have update to set up the DBInterface");
  };

  DBInterface.prototype["delete"] = function(criteria, cb) {
    throw Error("Implementations shoud have delete to set up the DBInterface");
  };

  return DBInterface;

})();

module.exports = DBInterface;
