// Generated by CoffeeScript 1.7.1
(function() {
  var FieldValidator, IpValidator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FieldValidator = require('./index').FieldValidator;

  IpValidator = (function(_super) {
    __extends(IpValidator, _super);

    function IpValidator(field) {
      this.errorMessage = "Field \"{{field}}\" should be valid IP ";
    }

    IpValidator.prototype.doValidate = function(data) {
      return data.match(/^\d\d?\d?\.\d\d?\d?\.\d\d?\d?\.\d\d?\d?$/) !== null;
    };

    return IpValidator;

  })(FieldValidator);

  module.exports = IpValidator;

}).call(this);
