// Generated by CoffeeScript 1.7.1
var FieldValidator, RequiredValidator,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FieldValidator = require('./index').FieldValidator;

RequiredValidator = (function(_super) {
  __extends(RequiredValidator, _super);

  function RequiredValidator() {
    this.errorMessage = "Field \"{{field}}\" is required";
  }

  RequiredValidator.prototype.doValidate = function(data) {
    return (data != null) && data.match(/\w/) !== null;
  };

  return RequiredValidator;

})(FieldValidator);

module.exports = RequiredValidator;
