// Generated by CoffeeScript 1.7.1
var MongoDB, mongoose;

mongoose = require('mongoose');

MongoDB = (function() {
  function MongoDB(DBUrl, DBName) {
    this.DBUrl = DBUrl;
    this.DBName = DBName;
  }

  MongoDB.prototype.createConnection = function() {
    var conn;
    conn = mongoose.createConnection('mongodb://localhost/test');
    conn.Schema = mongoose.Schema;
    return conn;
  };

  return MongoDB;

})();

module.exports = MongoDB;
