// Generated by CoffeeScript 1.7.1
var Database, MongoDB, mongoose,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

mongoose = require('mongoose');

Database = require('../../db');

MongoDB = (function(_super) {
  __extends(MongoDB, _super);

  function MongoDB(dbHost, dbName) {
    this.dbHost = dbHost;
    this.dbName = dbName;
    this.conn = mongoose.createConnection(this.dbHost + this.dbName);
    this.conn.Schema = mongoose.Schema;
  }

  MongoDB.prototype.registerSchema = function() {
    return this.conn;
  };

  return MongoDB;

})(Database);

module.exports = MongoDB;
