// Generated by CoffeeScript 1.7.1
var Schema;

Schema = (function() {
  function Schema(dbBackend, schemaName, schema) {
    this.schemaName = schemaName;
    this.schema = schema;
    this.conn = dbBackend.registerSchema();
    this.model = this.conn.model(this.schemaName, this.schema);
  }

  Schema.prototype.getModel = function() {
    return this.model;
  };

  return Schema;

})();

module.exports = Schema;
