// Generated by CoffeeScript 1.7.1
(function() {
  var objval;

  module.exports = objval = function(data, key) {
    var keys, newObj;
    keys = key.split(/\./);
    newObj = data[keys.shift()];
    if (keys.length < 1 || newObj === null) {
      return newObj;
    }
    if (typeof newObj === 'string' && keys.length >= 1) {
      return null;
    }
    return objval(newObj, keys.join('.'));
  };

}).call(this);
