// Generated by CoffeeScript 1.7.1
(function() {
  var setobjval;

  module.exports = setobjval = function(data, key, newVal) {
    var firstKey, keys;
    keys = key.split(/\./);
    firstKey = keys.shift();
    if (keys.length < 1) {
      data[firstKey] = newVal;
    }
    if (typeof data[firstKey] !== 'object' && keys.length > 0) {
      data[firstKey] = {};
    }
    if (keys.length > 0) {
      data[firstKey] = setobjval(data[firstKey], keys.join('.'), newVal);
    }
    return data;
  };

}).call(this);
